name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v2

      - name: Configurar Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: vinizanindev 
          svg_out_path: dist/snake.svg

      - name: Fazer upload da animação
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/snake.svg
